### ISSUE TITLE
download dataset

### ISSUE THREAD

**Issue by piaohe111** [vpulab/Semantic-Aware-Scene-Recognition#8]
I can not download the dataset such as  ADE20K , could you check that problem ?  I am in China .Thank you very much !

**Comment by piaohe111** [comment]
Sorry,I didn't finish reading the documentation.Now I can use sh file to download the dataset. the another queston is what does the semantic_score mean,if it is prob predicted by semantic network, the sum of its value must be 1,but I see there is a sample whose semantic_score is [0.0,0.0,0.392],I do not know what this value mean .hope to get your reply !

**Comment by alexlopezcifuentes** [comment]
Those values are indeed semantic probabilities obtained by the semantic network. However, in the proposed method only the Top 3 semantic predictions are used (the actual model retrieves 150 semantic classes). That's why those 3 scores do not sum up to 1.

The paper contains further information about this.
